<a href="https://colab.research.google.com/github/camilacruz-cs/python-para-inovacao-civica/blob/main/desafio_semana1_python_inovacao_civica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Explorando dados

Neste desafio colocaremos em prática alguns conceitos apresentado nas aulas. Para isso, usaremos o conjunto de dados [Candidatos - 2022](https://dadosabertos.tse.jus.br/dataset/candidatos-2022) disponível no Portal de Dados Abertos do Tribunal Superior Eleitoral.

Os dados também podem ser encontrados na pasta "Dados" deste repositório.

Siga as orientações abaixo para completar o desafio:

# Importe os pacotes necessários

In [2]:
import pandas as pd
import glob as gb

# Crie uma lista com o título dos arquivos usando a biblioteca Gloob

In [12]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [13]:
#Aqui estou chmando todos os arquivos.
#O título do arquivo precisa começar com 'consulta_cand' e finalizar com '.csv'
consulta_cand = gb.glob('/content/consulta_cand_2022_PA.csv')

In [14]:
print(consulta_cand)

['/content/consulta_cand_2022_PA.csv']

# Crie um laço (loop) para ler todos os arquivos da lista (usando a biblioteca Pandas) e armazenar os dataframes em uma lista

In [15]:
from IPython.utils import encoding
lista_estados = []

for dados_consulta in consulta_cand:
  df_lista = pd.read_csv(dados_consulta, sep=';', encoding='latin_1')
  lista_estados.append(df_lista)

In [16]:
print(lista_estados)

[      DT_GERACAO HH_GERACAO  ANO_ELEICAO  CD_TIPO_ELEICAO    NM_TIPO_ELEICAO  \
0     13/05/2023   19:32:48         2022                2  ELEIÇÃO ORDINÁRIA
1     13/05/2023   19:32:48         2022                2  ELEIÇÃO ORDINÁRIA
2     13/05/2023   19:32:48         2022                2  ELEIÇÃO ORDINÁRIA
3     13/05/2023   19:32:48         2022                2  ELEIÇÃO ORDINÁRIA
4     13/05/2023   19:32:48         2022                2  ELEIÇÃO ORDINÁRIA
...          ...        ...          ...              ...                ...
1038  13/05/2023   19:32:48         2022                2  ELEIÇÃO ORDINÁRIA
1039  13/05/2023   19:32:48         2022                2  ELEIÇÃO ORDINÁRIA
1040  13/05/2023   19:32:48         2022                2  ELEIÇÃO ORDINÁRIA
1041  13/05/2023   19:32:48         2022                2  ELEIÇÃO ORDINÁRIA
1042  13/05/2023   19:32:48         2022                2  ELEIÇÃO ORDINÁRIA

      NR_TURNO  CD_ELEICAO                      DS_ELEICAO  DT_ELEICAO  \
0            1         546  Eleições Gerais Estaduais 2022  02/10/2022
1            1         546  Eleições Gerais Estaduais 2022  02/10/2022
2            1         546  Eleições Gerais Estaduais 2022  02/10/2022
3            1         546  Eleições Gerais Estaduais 2022  02/10/2022
4            1         546  Eleições Gerais Estaduais 2022  02/10/2022
...        ...         ...                             ...         ...
1038         1         546  Eleições Gerais Estaduais 2022  02/10/2022
1039         1         546  Eleições Gerais Estaduais 2022  02/10/2022
1040         1         546  Eleições Gerais Estaduais 2022  02/10/2022
1041         1         546  Eleições Gerais Estaduais 2022  02/10/2022
1042         1         546  Eleições Gerais Estaduais 2022  02/10/2022

     TP_ABRANGENCIA  ...          NR_PROCESSO CD_SITUACAO_CANDIDATO_PLEITO  \
0          ESTADUAL  ...  6006408620226140000                            2
1          ESTADUAL  ...  6011397020226140000                           -1
2          ESTADUAL  ...  6012245620226140000                           -1
3          ESTADUAL  ...  6006754620226140000                            2
4          ESTADUAL  ...  6008876720226140000                            2
...             ...  ...                  ...                          ...
1038       ESTADUAL  ...  6002268820226140000                            2
1039       ESTADUAL  ...  6005637720226140000                            4
1040       ESTADUAL  ...  6004866820226140000                            2
1041       ESTADUAL  ...  6004312020226140000                            2
1042       ESTADUAL  ...  6009040620226140000                            2

     DS_SITUACAO_CANDIDATO_PLEITO  CD_SITUACAO_CANDIDATO_URNA  \
0                        DEFERIDO                           2
1                          #NULO#                          -1
2                          #NULO#                          -1
3                        DEFERIDO                           2
4                        DEFERIDO                           2
...                           ...                         ...
1038                     DEFERIDO                           2
1039       INDEFERIDO COM RECURSO                           4
1040                     DEFERIDO                           2
1041                     DEFERIDO                           2
1042                     DEFERIDO                           2

     DS_SITUACAO_CANDIDATO_URNA  ST_CANDIDATO_INSERIDO_URNA  \
0                      DEFERIDO                         SIM
1                        #NULO#                         NÃO
2                        #NULO#                         NÃO
3                      DEFERIDO                         SIM
4                      DEFERIDO                         SIM
...                         ...                         ...
1038                   DEFERIDO                         SIM
1039     INDEFERIDO COM RECURSO                         SIM
1040                   DEFERIDO                         SIM
1041                   DEFERIDO                         SIM
1042                   DEFERIDO                         SIM

      NM_TIPO_DESTINACAO_VOTOS CD_SITUACAO_CANDIDATO_TOT  \
0                       Válido                         2
1                       #NULO#                        -1
2                       #NULO#                        -1
3                       Válido                         2
4                       Válido                         2
...                        ...                       ...
1038                    Válido                         2
1039        Anulado sub judice                         4
1040                    Válido                         2
1041                    Válido                         2
1042                    Válido                         2

     DS_SITUACAO_CANDIDATO_TOT ST_PREST_CONTAS
0                     Deferido               S
1                       #NULO#               N
2                       #NULO#               N
3                     Deferido               S
4                     Deferido               S
...                        ...             ...
1038                  Deferido               S
1039    Indeferido com recurso               N
1040                  Deferido               S
1041                  Deferido               S
1042                  Deferido               S

[1043 rows x 71 columns]]

# Concatene todos os dataframes da lista

In [18]:
df_completo = pd.concat(lista_estados, axis=0, ignore_index=True)

In [19]:
df_completo.shape

(1043, 71)

In [17]:
df_completo.head()

,DT_GERACAO,HH_GERACAO,AA_ELEICAO,SG_UF,CD_TIPO_ELEICAO,NM_TIPO_ELEICAO,CD_ELEICAO,DS_ELEICAO,SQ_CANDIDATO,NR_ORDEM,DS_URL
0,04/07/2023,19:51:29,2022,DF,2,ELEIÇÃO ORDINÁRIA,546,ELEIÇÕES GERAIS ESTADUAIS 2022,70001650793,5,https://instagram.com/tadeufilippellireal
1,04/07/2023,19:51:29,2022,DF,2,ELEIÇÃO ORDINÁRIA,546,ELEIÇÕES GERAIS ESTADUAIS 2022,70001650793,6,https://www.filippellireal.com.br
2,04/07/2023,19:51:29,2022,DF,2,ELEIÇÃO ORDINÁRIA,546,ELEIÇÕES GERAIS ESTADUAIS 2022,70001650793,1,https://mobilie.twitter.com/filippellireal
3,04/07/2023,19:51:29,2022,DF,2,ELEIÇÃO ORDINÁRIA,546,ELEIÇÕES GERAIS ESTADUAIS 2022,70001650793,3,https://www.tiktok.com/@tadeufilippellireal
4,04/07/2023,19:51:29,2022,DF,2,ELEIÇÃO ORDINÁRIA,546,ELEIÇÕES GERAIS ESTADUAIS 2022,70001650793,4,https://www.facebook.com/tadeufilippellireal

# Apresente 5 linhas aleatórias do dataframe

In [20]:
df_completo.head(5)

,DT_GERACAO,HH_GERACAO,ANO_ELEICAO,CD_TIPO_ELEICAO,NM_TIPO_ELEICAO,NR_TURNO,CD_ELEICAO,DS_ELEICAO,DT_ELEICAO,TP_ABRANGENCIA,...,NR_PROCESSO,CD_SITUACAO_CANDIDATO_PLEITO,DS_SITUACAO_CANDIDATO_PLEITO,CD_SITUACAO_CANDIDATO_URNA,DS_SITUACAO_CANDIDATO_URNA,ST_CANDIDATO_INSERIDO_URNA,NM_TIPO_DESTINACAO_VOTOS,CD_SITUACAO_CANDIDATO_TOT,DS_SITUACAO_CANDIDATO_TOT,ST_PREST_CONTAS
0,13/05/2023,19:32:48,2022,2,ELEIÇÃO ORDINÁRIA,1,546,Eleições Gerais Estaduais 2022,02/10/2022,ESTADUAL,...,6006408620226140000,2,DEFERIDO,2,DEFERIDO,SIM,Válido,2,Deferido,S
1,13/05/2023,19:32:48,2022,2,ELEIÇÃO ORDINÁRIA,1,546,Eleições Gerais Estaduais 2022,02/10/2022,ESTADUAL,...,6011397020226140000,-1,#NULO#,-1,#NULO#,NÃO,#NULO#,-1,#NULO#,N
2,13/05/2023,19:32:48,2022,2,ELEIÇÃO ORDINÁRIA,1,546,Eleições Gerais Estaduais 2022,02/10/2022,ESTADUAL,...,6012245620226140000,-1,#NULO#,-1,#NULO#,NÃO,#NULO#,-1,#NULO#,N
3,13/05/2023,19:32:48,2022,2,ELEIÇÃO ORDINÁRIA,1,546,Eleições Gerais Estaduais 2022,02/10/2022,ESTADUAL,...,6006754620226140000,2,DEFERIDO,2,DEFERIDO,SIM,Válido,2,Deferido,S
4,13/05/2023,19:32:48,2022,2,ELEIÇÃO ORDINÁRIA,1,546,Eleições Gerais Estaduais 2022,02/10/2022,ESTADUAL,...,6008876720226140000,2,DEFERIDO,2,DEFERIDO,SIM,Válido,2,Deferido,S

# Quantas candidaturas estão em situação de reeleição?

In [21]:
#Aqui, quero descobrir quais são as colunas existentes no DF e também, conseguir descobrir qual teria a reeleição.

df_completo.columns

Index(['DT_GERACAO', 'HH_GERACAO', 'ANO_ELEICAO', 'CD_TIPO_ELEICAO',
       'NM_TIPO_ELEICAO', 'NR_TURNO', 'CD_ELEICAO', 'DS_ELEICAO', 'DT_ELEICAO',
       'TP_ABRANGENCIA', 'SG_UF', 'SG_UE', 'NM_UE', 'CD_CARGO', 'DS_CARGO',
       'SQ_CANDIDATO', 'NR_CANDIDATO', 'NM_CANDIDATO', 'NM_URNA_CANDIDATO',
       'NM_SOCIAL_CANDIDATO', 'NR_CPF_CANDIDATO', 'NM_EMAIL',
       'CD_SITUACAO_CANDIDATURA', 'DS_SITUACAO_CANDIDATURA',
       'CD_DETALHE_SITUACAO_CAND', 'DS_DETALHE_SITUACAO_CAND', 'TP_AGREMIACAO',
       'NR_PARTIDO', 'SG_PARTIDO', 'NM_PARTIDO', 'NR_FEDERACAO',
       'NM_FEDERACAO', 'SG_FEDERACAO', 'DS_COMPOSICAO_FEDERACAO',
       'SQ_COLIGACAO', 'NM_COLIGACAO', 'DS_COMPOSICAO_COLIGACAO',
       'CD_NACIONALIDADE', 'DS_NACIONALIDADE', 'SG_UF_NASCIMENTO',
       'CD_MUNICIPIO_NASCIMENTO', 'NM_MUNICIPIO_NASCIMENTO', 'DT_NASCIMENTO',
       'NR_IDADE_DATA_POSSE', 'NR_TITULO_ELEITORAL_CANDIDATO', 'CD_GENERO',
       'DS_GENERO', 'CD_GRAU_INSTRUCAO', 'DS_GRAU_INSTRUCAO',
       'CD_ESTADO_CIVIL', 'DS_ESTADO_CIVIL', 'CD_COR_RACA', 'DS_COR_RACA',
       'CD_OCUPACAO', 'DS_OCUPACAO', 'VR_DESPESA_MAX_CAMPANHA',
       'CD_SIT_TOT_TURNO', 'DS_SIT_TOT_TURNO', 'ST_REELEICAO',
       'ST_DECLARAR_BENS', 'NR_PROTOCOLO_CANDIDATURA', 'NR_PROCESSO',
       'CD_SITUACAO_CANDIDATO_PLEITO', 'DS_SITUACAO_CANDIDATO_PLEITO',
       'CD_SITUACAO_CANDIDATO_URNA', 'DS_SITUACAO_CANDIDATO_URNA',
       'ST_CANDIDATO_INSERIDO_URNA', 'NM_TIPO_DESTINACAO_VOTOS',
       'CD_SITUACAO_CANDIDATO_TOT', 'DS_SITUACAO_CANDIDATO_TOT',
       'ST_PREST_CONTAS'],
      dtype='object')

In [23]:
df_completo['ST_REELEICAO'].unique()

array(['N', 'S', 'Não divulgável'], dtype=object)

In [24]:
df_completo['ST_REELEICAO'].value_counts()

N                 989
S                  53
Não divulgável      1
Name: ST_REELEICAO, dtype: int64

# Liste todas a ocupações declaradas pelas candidaturas

In [27]:
df_completo.DS_CARGO.value_counts()

DEPUTADO ESTADUAL    652
DEPUTADO FEDERAL     323
1º SUPLENTE           19
2º SUPLENTE           18
SENADOR               12
VICE-GOVERNADOR       10
GOVERNADOR             9
Name: DS_CARGO, dtype: int64

In [28]:
#Utilizando filtros

candidaturas_dep_fed = df_completo[
    df_completo['DS_CARGO'] == 'DEPUTADO FEDERAL'
].copy()

#aqui se usa o copy para preservar o DF criado primeiro

In [32]:
candidaturas_dep_fed['DS_CARGO'].unique()

array(['DEPUTADO FEDERAL'], dtype=object)

# Quantos anos tem a pessoa candidata mais velha?

In [33]:
df_completo.NR_IDADE_DATA_POSSE.max()

81.0

# Quantos anos tem a pessoa candidata mais jovem?

In [34]:
df_completo.NR_IDADE_DATA_POSSE.min()

19.0

# Qual é o nome da pessoa candidata mais velha?

In [37]:
candidaturas_idade = df_completo[
    df_completo['NR_IDADE_DATA_POSSE'] == 81
].copy()

In [38]:
candidaturas_idade['NM_CANDIDATO']

49    MARIA DE LOURDES PEREIRA DE FARIAS
Name: NM_CANDIDATO, dtype: object

# Quantas candidaturas existem para "Deputado federal" seu estado?

In [39]:
candidaturas_dep_fed = df_completo[
    df_completo['DS_CARGO'] == 'DEPUTADO FEDERAL'
].copy()

In [47]:
candidaturas_dep_fed['DS_CARGO'].count()

323

# Qual é a média do valor máximo de despesas de campanha?

In [51]:
media = df_completo["VR_DESPESA_MAX_CAMPANHA"].mean()

In [53]:
#Arrendondamento

round(media,1)

1928968.3