<a href="https://colab.research.google.com/github/camilacruz-cs/python-para-inovacao-civica/blob/main/semana_2_estatistica_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Introdução à Estatística

In [ ]:
import pandas as pd

In [ ]:
candidatos = ['/content/consulta_cand_2016_AP.csv']

In [ ]:
candidatura_2016 = []

for dados in candidatos:
  dados_completos = pd.read_csv(dados, sep =';', encoding = 'latin_1')
  candidatura_2016.append(dados_completos)

In [ ]:
print(candidatura_2016)

[      DT_GERACAO HH_GERACAO  ANO_ELEICAO  CD_TIPO_ELEICAO    NM_TIPO_ELEICAO  \
0     13/03/2023   15:28:45         2016                2  ELEIÇÃO ORDINÁRIA
1     13/03/2023   15:28:45         2016                2  ELEIÇÃO ORDINÁRIA
2     13/03/2023   15:28:45         2016                2  ELEIÇÃO ORDINÁRIA
3     13/03/2023   15:28:45         2016                2  ELEIÇÃO ORDINÁRIA
4     13/03/2023   15:28:45         2016                2  ELEIÇÃO ORDINÁRIA
...          ...        ...          ...              ...                ...
1885  13/03/2023   15:28:45         2016                2  ELEIÇÃO ORDINÁRIA
1886  13/03/2023   15:28:45         2016                2  ELEIÇÃO ORDINÁRIA
1887  13/03/2023   15:28:45         2016                2  ELEIÇÃO ORDINÁRIA
1888  13/03/2023   15:28:45         2016                2  ELEIÇÃO ORDINÁRIA
1889  13/03/2023   15:28:45         2016                2  ELEIÇÃO ORDINÁRIA

      NR_TURNO  CD_ELEICAO                DS_ELEICAO  DT_ELEICAO  \
0            1         220  Eleições Municipais 2016  02/10/2016
1            1         220  Eleições Municipais 2016  02/10/2016
2            1         220  Eleições Municipais 2016  02/10/2016
3            1         220  Eleições Municipais 2016  02/10/2016
4            1         220  Eleições Municipais 2016  02/10/2016
...        ...         ...                       ...         ...
1885         1         220  Eleições Municipais 2016  02/10/2016
1886         1         220  Eleições Municipais 2016  02/10/2016
1887         1         220  Eleições Municipais 2016  02/10/2016
1888         1         220  Eleições Municipais 2016  02/10/2016
1889         1         220  Eleições Municipais 2016  02/10/2016

     TP_ABRANGENCIA  ...       NR_PROCESSO  CD_SITUACAO_CANDIDATO_PLEITO  \
0         MUNICIPAL  ...  1240420166030010                             2
1         MUNICIPAL  ...  1084720166030011                             2
2         MUNICIPAL  ...  3198620166030010                             2
3         MUNICIPAL  ...  6281020166030010                             2
4         MUNICIPAL  ...  1528720166030004                             2
...             ...  ...               ...                           ...
1885      MUNICIPAL  ...   939020166030007                             2
1886      MUNICIPAL  ...  2879320166030006                             2
1887      MUNICIPAL  ...   731120166030004                             2
1888      MUNICIPAL  ...  1207920166030005                             2
1889      MUNICIPAL  ...  1199120166030006                             2

     DS_SITUACAO_CANDIDATO_PLEITO  CD_SITUACAO_CANDIDATO_URNA  \
0                        DEFERIDO                           2
1                        DEFERIDO                           2
2                        DEFERIDO                           2
3                        DEFERIDO                          17
4                        DEFERIDO                           2
...                           ...                         ...
1885                     DEFERIDO                           2
1886                     DEFERIDO                           2
1887                     DEFERIDO                           2
1888                     DEFERIDO                           2
1889                     DEFERIDO                           2

     DS_SITUACAO_CANDIDATO_URNA  ST_CANDIDATO_INSERIDO_URNA  \
0                      DEFERIDO                         SIM
1                      DEFERIDO                         SIM
2                      DEFERIDO                         SIM
3        PENDENTE DE JULGAMENTO                         SIM
4                      DEFERIDO                         SIM
...                         ...                         ...
1885                   DEFERIDO                         SIM
1886                   DEFERIDO                         SIM
1887                   DEFERIDO                         SIM
1888                   DEFERIDO                         SIM
1889                   DEFERIDO                         SIM

      NM_TIPO_DESTINACAO_VOTOS CD_SITUACAO_CANDIDATO_TOT  \
0                       Válido                         2
1                       Válido                         2
2                       Válido                         2
3                       Válido                         2
4                       Válido                         2
...                        ...                       ...
1885                    Válido                         2
1886                    Válido                         2
1887                    Válido                         2
1888                    Válido                         2
1889                    Válido                         2

     DS_SITUACAO_CANDIDATO_TOT ST_PREST_CONTAS
0                     Deferido               S
1                     Deferido               S
2                     Deferido               S
3                     Deferido               S
4                     Deferido               S
...                        ...             ...
1885                  Deferido               S
1886                  Deferido               S
1887                  Deferido               S
1888                  Deferido               S
1889                  Deferido               S

[1890 rows x 71 columns]]

### 2.8 Operações com dados e groupby

Sintaxe: dataframe.groupby(“lista_colunas_agrupamento”).funcao

### Algumas perguntas que queremos responder



1.   Quantas mulheres são candidatas?
2.   Qual a distribuição de pessoas por grupo racial?
3.   Quantidade de mulheres por grupo racial?
4.   E qual partido tem mais mulheres em cada grupo racial?

In [ ]:
#Aqui eu seleciono todas as colunas que eu quero que sejam associadas ao meu filtro desejado.
colunas_desejadas = ['SG_PARTIDO', 'DS_GENERO', 'DS_COR_RACA']
filtro = dados_completos['SG_PARTIDO'] == 'AP'

In [ ]:
candidatos_sexo_raca = dados_completos.loc[filtro, colunas_desejadas]
candidatos_sexo_raca

Empty DataFrame
Columns: [SG_PARTIDO, DS_GENERO, DS_COR_RACA]
Index: []

In [ ]:
#Agrupamento pela variável gênero.
candidatos_sexo_raca.groupby(['DS_GENERO']).count()

Empty DataFrame
Columns: [SG_PARTIDO, DS_COR_RACA]
Index: []

In [ ]:
candidatos_sexo_raca.groupby(['DS_COR_RACA']).count()

Empty DataFrame
Columns: [SG_PARTIDO, DS_GENERO]
Index: []

In [ ]:
candidatos_sexo_raca[candidatos_sexo_raca['DS_GENERO'] == 'FEMININO'].groupby(
    ['DS_GENERO', 'DS_COR_RACA']).count()

Empty DataFrame
Columns: [SG_PARTIDO]
Index: []

In [ ]:
#E se quisermos descobrir, quais os partidos que possuem o maior número de representação em cada grupo social?

candidatos_sexo_raca[candidatos_sexo_raca['DS_GENERO'] == 'FEMININO'].groupby(
    ['DS_GENERO', 'DS_COR_RACA']).max()

Empty DataFrame
Columns: [SG_PARTIDO]
Index: []